### PR TITLE
fastboot: reboot bootloader: add stuff for imx8

### PR DESCRIPTION
**Pull request by grassead**
Add reboot flag function for imx8.
This is necessary for "fastboot reboot bootloader"
command.

Signed-off-by: Adrien Grassein <adrien.grassein@smile.fr>

### CODE REVIEW

**Comment by gibsson** [comment]
Hi Adrien,
Thanks for your contribution. I'll let @tkisky decide on this one as U-Boot is his.
However I believe he'd rather include the upstream solution:
https://github.com/u-boot/u-boot/commit/0ebf9842
Note that we plan on updating to latest U-Boot really soon so better make use of those latest upstream patches now I think.
Regards,
Gary

**Comment by grassead** [comment]
Hi Gary,

Before to do my patch, I tried to backport this onto the BD branch but this requires to port a lot of patches on several boards.
I think that  it's a good compromise on this version of u-boot. (This is needed to fix a bug in the BD flash script).

About the migration on a new version, do you need some help (code, test, other). I currently have some time and an nitrogen 8 mini.

Thanks,

**Comment by grassead** [comment]
Hi,

Should I consider the "no answer" as a "we do not merge your branch" ?
I am OK to close it to not let it opened indefinitely.

Thanks,

**Comment by gibsson** [comment]
Hi,
No it doesn't mean we won't merge it, it means we haven't had time to look at it properly yet. Mainly we want to verify how much effort it is to backport upstream patches.
Regards

**Comment by grassead** [comment]
Hi,

Ok  no problem, good luck for the migration.

If you need some help (test, dev or other), don't hesitate to ask (i now have a nitrogem8m mini and a nitrgoen8m)

Thanks again.

**Comment by gibsson** [comment]
Hi,
The patch was merged here:
https://github.com/boundarydevices/u-boot-imx6/commit/5a0a94df3748b6247579d5e2f1398e944f71c6c6
I modified the title to be a bit more accurate (imx8m vs. imx8) and also made it clear this patch won't be ported to newer version as unnecessary.
Thanks again

**Comment by grassead** [comment]
Thanks.

**Pull request closed without merging**
