### PR TITLE
Add CONFIG_CMD_EXT4 and CONFIG_CMD_FS_GENERIC

### PR DESCRIPTION
**Pull request by kmihelich**
Added support for reading from ext4 partitions, and updated the environment to take advantage of the 'load' command from FS_GENERIC. This will autodetect the filesystem type removes the need to test loading each type separately.

### CODE REVIEW

**Comment by ericnelsonaz** [comment]
Hi Kevin,

Sorry for the delayed response.

We've seen some issues related to the use of the generic load command, though it's been a long while (~6 months) since we tested and some fixes have been made to ext2/3/4 support that may address the issue.

I believe the issues were related to the use of dcache.

We also can't merge this patch without corresponding boot script updates, since most boot scripts make use of the ${fs} variable.

**Comment by ericnelsonaz** [comment]
Hi Kevin,

Can you split this into two patches: (add CONFIGs, change environment)?

There's no reason not to pull the first into our staging branch, or for that matter, sending it up-stream. If the default environment doesn't use them, there's no danger.

**Comment by kmihelich** [comment]
So far I haven't seen any loading issue with fs_generic on the Nitrogen6X using a U-Boot built with these changes.  I also haven't seen any problems with it on other platforms where this is enabled and used.

If scripts are using the ${fs} variable, since this isn't set with this patch anymore it will get interpreted out as nothing when a script with that variable is sourced.  An "${fs}load" instance in the script will just change to "load".  I just tested with these changes in my U-Boot and using ${fs}load for loading the zImage and dtb, and the script continues to work fine using an ext4 partition.  I don't believe there were any other uses of ${fs} in the scripts I've seen other than loading.

I can split the changes into two parts and do a PR against the staging branch.

**Comment by ericnelsonaz** [comment]
Hi Kevin,

On Mon, May 5, 2014 at 10:27 AM, Kevin Mihelich notifications@github.comwrote:

> So far I haven't seen any loading issue with fs_generic on the Nitrogen6X
> using a U-Boot built with these changes. I also haven't seen any problems
> with it on other platforms where this is enabled and used.
> 
> Again, our testing was from 6 months ago, and the last couple of releases
> have had some work in this area.
> 
> If scripts are using the ${fs} variable, since this isn't set with this
> patch anymore it will get interpreted out as nothing when a script with
> that variable is sourced. An "${fs}load" instance in the script will just
> change to "load". I just tested with these changes in my U-Boot and using
> ${fs}load for loading the zImage and dtb, and the script continues to work
> fine using an ext4 partition. I don't believe there were any other uses of
> ${fs} in the scripts I've seen other than loading.

Doh! I hadn't thought through what the effect would be, and I suspect
you're right.

> I can split the changes into two parts and do a PR against the staging
> branch.
> 
> Thanks muchly.

I'll forward them on to the U-Boot ML. Do you follow that list?

Please advise,

Eric

**Comment by kmihelich** [comment]
Sent two new PRs with each separate part for merging separately.

I don't follow the U-Boot ML at the moment, but I'll add that to the rest that I do.

**Comment by ericnelsonaz** [comment]
No worries Kevin.

I'll push this through to the list and get it up-streamed (with your SOB).

**Pull request closed without merging**
